### ISSUE TITLE
Change <img /> reset

### ISSUE THREAD

**Issue by mrluisfer** [mrLuisFer/me-bento#8]
Extend the <img /> reset, even in the <Img /> component, using
```css
img {
  max-width: 100%;
  height: auto;
  vertical-align: middle;
  font-style: italic;
  background-repeat: no-repeat;
  background-size: cover;
  margin-shape: 0.75rem;
}
```
Look for any problems this might throw
